### ISSUE TITLE
Failed to activate the rempl-host package

### ISSUE THREAD

**Issue by sergei-iakimenko** [rempl/host-atom#3]
[Enter steps to reproduce:]

1. Trouble disappears just during install.

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Windows 10 Pro
**Thrown From**: [rempl-host](https://github.com/rempl/host-atom) package 0.3.0

### Stack Trace

Failed to activate the rempl-host package

```
At [rempl] createEnv() doesn't supported for node.js

Error: [rempl] createEnv() doesn't supported for node.js
    at createEnv (/packages/rempl-host/node_modules/rempl/src/env/index.js:12:19)
    at RemplClient.initEnv (/packages/rempl-host/lib/index.js:80:20)
    at RemplClient.activate (/packages/rempl-host/lib/index.js:40:14)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.21.0/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.21.0/resources/app/src/package-manager.js:690:42)
    at ~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (~/AppData/Local/atom/app-1.21.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.21.0/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -1:50.6.0 core:cancel (div.package-detail.panels-item)
     -1:40.9.0 core:select-all (input.hidden-input)
     -1:40.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
rempl-host 0.3.0 
```

**Comment by davidehuey** [comment]
(0 , _rempl.createEnv) is not a function
Hide Stack Trace
TypeError: (0 , _rempl.createEnv) is not a function
    at RemplClient.initEnv (file:///C:/Users/HP/.atom/packages/rempl-host/lib/index.js:80:20)
    at RemplClient.activate (file:///C:/Users/HP/.atom/packages/rempl-host/lib/index.js:40:14)
    at Package.activateNow (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:3287884)
    at C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:3287296
    at Package.measure (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:3284906)
    at C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:3287156
    at new Promise (<anonymous>)
    at Package.activate (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:3287099)
    at PackageManager.activatePackage (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:382942)
    at C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:382558
    at Config.transactAsync (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:332206)
    at PackageManager.activatePackages (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:382508)
    at PackageManager.activate (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:11:382058)
    at C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:1:757178
    at async Promise.all (index 0)
    at AtomEnvironment.startEditorWindow (C:\Users\HP\AppData\Local\atom\app-1.50.0\resources\app\static\<embedded>:1:757663)
